### PR TITLE
Population data pipeline

### PR DESCRIPTION
**Pull request by milafrerichs**
## What does this PR do?

It adds a new folder for data pipelines. And uses a makefile to get the data from the Worldbank API and transform the resulting JSON to CSV.

@gsilvapt I followed the project and thought it might be easier to use the API as @mcallaghan suggested and used my knowledge of Makefiles and csvkit to make a repeatable data pipeline.

### CODE REVIEW

**Comment by gsilvapt** [comment]
Hi Mila! Thanks for contributing.

I'm not a Python expert, so I must ask: Aside from fetching data directly from the GitHub, which is always a plus, what does this do that is different from what we have?

Also, to convert data into datapackages, we need a JSON file. Perhaps we can include both mechanisms into one single python script (that is, fetch, create a csv and a datapackage.json file)?

**Comment by milafrerichs** [comment]
Hey @gsilvapt 

Yeah. No problem. 
What you were doing is to scrape the data from the website which is always more prone to errors. By using the API and getting the data directly from the Worldbank, we can make sure the data is clean. 

And this is not a python script but a pure shell script so it can run without having to install python on a server. 

I have a JSON file already since the API is serving JSON but I did not save it.

**Comment by gsilvapt** [comment]
Is it possible to do this along the Python script to create datasets? It is
in another repository of this organization, if you need to have a look

Best Regards / Obrigado e com os melhores cumprimentos,
Gustavo Silva

2016-01-23 14:10 GMT+00:00 Mila Frerichs <notifications@github.com>:

**Comment by milafrerichs** [comment]
Not sure I understood. 
To create a `datapackage.json` from the csv?

**Comment by gsilvapt** [comment]
Sort of.
The datapackage repository I meant is the one that has been adapted from
OKFN's to make it simpler. It creates a .json file and it also writes some
of the information it needs to be posted as a dataset. You can have look in
here: https://github.com/okfn-oe/datapackage-validator The readme and/or
introduction may be incomplete, but there has been too many fronts for me
to focus on, so I cannot handle everything :D

With that script, and with what you wrote there to Econ-Factbook, is it
possible to somehow combine them?

Best Regards / Obrigado e com os melhores cumprimentos,
Gustavo Silva

2016-01-23 14:20 GMT+00:00 Mila Frerichs <notifications@github.com>:

**Comment by milafrerichs** [comment]
Yes, already pushed the `datapackage.json` which was generated with the node tool `datapackage`
Is that what you wanted? :)

**Comment by gsilvapt** [comment]
I believe it was :) 

Thanks :+1: 

Now we need to do this for all data inputs we have on econfactbook.org

**Comment by milafrerichs** [comment]
Yes, correct. But should be very straighforward. As long as there is an API from the worldbank it's almost just copy and paste. (Maybe I create another Makefile that does it all at once :) )

**Comment by mcallaghan** [comment]
Could loop through this and get everything in WDIs... http://api.worldbank.org/source/2/indicators?format=json&per_page=2000.

Fraid I don't know makefiles very well, but should be fairly easy

**Pull request merged**
